# Generated by Django 5.0 on 2024-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
