# Generated by Django 5.0 on 2024-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_why_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
