# Generated by Django 5.0 on 2024-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='starters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_ingredients', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
