# Generated by Django 5.0 on 2024-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
