# Generated by Django 5.0 on 2024-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
