# Generated by Django 5.0 on 2024-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_professionals_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
    ]
