# Generated by Django 5.0 on 2024-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_galleries'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_success', models.BooleanField()),
                ('is_error', models.BooleanField()),
                ('action_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
