# Generated by Django 5.0 on 2024-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_booking_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_info',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_info',
            name='is_error',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_info',
            name='is_success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
